# Generated by Django 3.1.5 on 2021-06-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationFileUpload',
            new_name='FileUpload',
        ),
    ]
