# Generated by Django 3.1.5 on 2021-06-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0002_auto_20210608_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='category',
            field=models.IntegerField(choices=[(1, 'For Publication'), (2, 'For Meditation')], default=1),
        ),
    ]
