# Generated by Django 3.1.5 on 2021-08-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadFiles', '0003_auto_20210608_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='category',
        ),
    ]
