# Generated by Django 3.1.5 on 2021-03-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('EmailID', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('MobileNo', models.IntegerField(blank=True)),
                ('Password', models.CharField(max_length=24)),
                ('ConfirmPassword', models.CharField(max_length=24)),
            ],
        ),
    ]
