# Generated by Django 3.1.5 on 2021-03-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='Titles',
        ),
    ]
