# Generated by Django 3.1.5 on 2021-05-09 05:40

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_blog', '0002_auto_20210313_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='DefaultBlog.png', upload_to='BlogImg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='update_to',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Decscription',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
