# Generated by Django 3.1.5 on 2021-05-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_blog', '0003_auto_20210509_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Decscription',
            new_name='content',
        ),
    ]
