# Generated by Django 3.1.5 on 2021-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_blog', '0004_auto_20210509_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blogid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='comment',
            name='emailid',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
