# Generated by Django 3.1.5 on 2021-06-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetInTouch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('EmailId', models.CharField(max_length=100)),
                ('Message', models.TextField()),
            ],
        ),
    ]
