# Generated by Django 3.1.5 on 2021-06-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetInTouch', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='contactNo',
            field=models.CharField(default='0000000000y', max_length=10),
        ),
    ]
