# Generated by Django 3.1.5 on 2021-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetInTouch', '0003_bookappointment_contactno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='contactNo',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
