# Generated by Django 3.1.5 on 2021-01-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MeetMe', '0003_experiences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experiences',
        ),
        migrations.DeleteModel(
            name='Skillset',
        ),
    ]
