# Generated by Django 3.1.5 on 2021-06-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetMe', '0005_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(default='DefaultBlog.png', upload_to='PersonalImage'),
        ),
    ]
