# Generated by Django 3.1.5 on 2021-01-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiences',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='Rateing',
            field=models.IntegerField(max_length=100),
        ),
    ]
