# Generated by Django 3.1.5 on 2021-01-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0002_auto_20210124_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='designation',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='formDate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='organization_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='toDate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='Skill',
            field=models.CharField(max_length=100),
        ),
    ]
