# Generated by Django 3.1.5 on 2021-01-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0004_auto_20210125_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='formDate',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='toDate',
            field=models.DateField(max_length=20),
        ),
    ]
