# Generated by Django 3.1.5 on 2021-01-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanal', '0006_auto_20210125_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploadimage/photos/')),
            ],
        ),
    ]
